<?php 
    $_redirectURL = $this->getRedirectUrl();
    $_getOneTimeToken = $this->getOneTimeToken();
    $_currentURL = $this->getCurrentUrl();
?>
<form id="submitForm" method="post" action="<?php echo $_redirectURL ?>">
<input type="hidden" name="PaReq" value="<?php echo $_getOneTimeToken ?>"/>
<input type="hidden" id="termUrl" name="TermUrl" value="<?php echo $_currentURL;?>"/>
<script>parent.window.WorldpayMagento.showThreeDSIframe();document.getElementById("submitForm").submit();</script>
</form>
