<?php
    $code = $this->getMethodCode();
    $months = $this->getMonths();
    $years = $this->getExpiryYears();
    $clientKey = $this->getClientKey();
    $billingName = $this->getBillingName();
    $persistence = $this->getPersistence();
    $cards = $this->getCardsOnFile();
    $userIsLoggedIn = Mage::getSingleton('customer/session')->isLoggedIn();
    $threeDSEnabled = $this->getThreeDSEnabled();
    if (!$threeDSEnabled) {
        $threeDSEnabled = 0;
    }
?>
<ul class="form-list worldpay-container" id="payment_form_worldpay_cc" style="display:none">
    
    <input type="hidden" id="wp_token"  name="payment[token]" value="">
    <?php
     if (!empty($cards)):
        foreach ($cards as $card):
            echo '<li><span class="worldpay-savedcard-input"><input name="payment[savedcard]" type="radio" value="'. $card['token'] .'" id="token-'. $card['id'] .'"> <label for="token-'. $card['id'] .'">'. $card['cardType'] . ' - <span class="savedmber">'. $card['number'] .'</span></label></span></li>';
        endforeach;
    ?>
    <div style="display:none;" class="worldpay_existing_cvc_box" id="worldpay_existing_cvc_box">
        <div class="admin__field-control control" id="wp_cvc_container" style="width:270px;height:200px;overflow: hidden;"></div>
    </div>
    
    <li>
        <input type="radio" name="payment[savedcard]" id="worldpay-newcard" autocomplete="off">
        <label for="worldpay-newcard">Use a new card</label>
    </li>
    <?php endif; ?>

    <li class="validation-advice" style="display:none;" id="worldpay-payment-errors"></li>

    <?php if (!empty($cards)): ?>
    <ul id="new-worldpay-card" style="display:none;">
    <?php endif; ?>
    <div class="worldpay_existing_cvc_box">
    	<li id="worldpay-iframe">
           
        </li>
        
        <?php if ($persistence && $userIsLoggedIn) : ?>
            <p class="save-card"><label for="worldpay-savecard">Save Card</label> <input id="worldpay-savecard" type="checkbox" name="payment[savecard]" /></p>
            <p>Your card will be securely saved and can be removed at any time from your account.</p>
        <?php endif; ?>
    </div>
    <?php if (!empty($cards)): ?>

    </ul>
    <?php endif; ?>
</ul>

<script type="text/javascript">
if (!window.Worldpay) {
    alert('Worldpay JS not loaded!');
}
Worldpay.templateSaveButton = false;
Worldpay.setClientKey("<?php echo $clientKey; ?>");
<?php if ($persistence): ?>
Worldpay.reusable = true;
<?php endif; ?>
document.worldPayThreeDSEnabled = <?php echo $threeDSEnabled; ?>;
if (window.loadUpWP) {
    loadUpWP();
}
</script>
