<?php 
    $_country=$this->getBillingCountry();
    $_clientKey=$this->getClientKey(); 
?>
<ul class="form-list worldpay-container" id="payment_form_worldpay_giropay" style="display:none">

    <li class="header-message">
        <div class="security-message">
            <div class="message">
                <strong>Pay with Giropay</strong>
                <p>
                <label for="wp-swift-code">Swift code</label><br/>
                <input type="text" id="wp-swift-code" value="" />
                </p>
                <input type="hidden" id="wp-country-code" data-worldpay="country-code" value="<?php echo $_country; ?>" />
                <p>You will be redirected to Giropay to complete your purchase</p>
            </div>
        </div>
    </li>
</ul>

<script type="text/javascript">
if (!window.Worldpay) {
    alert('Worldpay JS not loaded!');
}
Worldpay.setClientKey("<?php echo $_clientKey; ?>");
Worldpay.tokenType = 'apm';
if (window.loadUpWP) {
    loadUpWP();
}
</script>
